# Generated by Django 4.2.2 on 2023-06-19 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id_question",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("options", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("tip", models.CharField(max_length=255)),
            ],
        ),
    ]
